### ISSUE TITLE
$window.joint is undefined

### ISSUE THREAD

**Issue by kevin-work** [elsix/angular-jointjs-graph#3]
Being quite new to Javascript and AngularJS in general I may be asking a silly question but nevertheless I cannot work out what the problem is. I just have one ```app.js``` which contains:

    (function () {
        'use strict';

        angular.module('app', ['ngResource', 'angular-jointjs-graph'])

        .controller('GraphResourcesController', ['GraphConfig', function() {}])

        .factory('GraphConfig', function() { return {} });
    })();

A bare page with (yes I have bootstrapped and included libraries):

    <div ng-controller="GraphResourcesController">  
        <graph config-factor="GraphConfig"></graph>
    </div>

I am getting the error mentioned in the title at:

    angular-jointjs-graph.js:1022:7

It is the only error I get.

**Comment by npetkov** [comment]
I'll try and reproduce the issue but as a quick reminder - have you installed all bower dependencies? If yes, are you serving them? It looks like the JointJs dependency is not met.

**Comment by kevin-work** [comment]
@npetkov Ahh yes it was that problem. I'm serving it through ASP.NET and couldn't quite translate the instructions across. The error is gone now. Thanks for the help!

**Comment by npetkov** [comment]
No problem, glad you sorted it out.
